version: '3'
services:
  Achat:
    image: SAIFEDDINELAYOUNI-5SIM3-G4-tpAchatProject
    restart: on-failure
    ports:
      - '8089:8089'
    depends_on:
      - mysql
    networks:
      - mynetwork
    volumes:
      - .m2:/root/.m2
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  .m2:
