version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: tpachato
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app-tpAchatProject:
    depends_on:
      - mysqldb
    image: aminesaadaoui/tpachatproject:1.0.0
    restart: on-failure
    ports:
     - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{

      }'
    stdin_open: true
    tty: true

volumes:
  db : {}